name: jsond
description: A template-supported tool for converting JSON to Dart code.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_core:
    path: ../../packages/core
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  sliver_tools: ^0.2.10
  extended_sliver: ^2.1.3
  code_text_field: ^1.1.0
  collection: ^1.17.0
  window_manager: ^0.3.2
  universal_platform: ^1.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flex_color_picker: ^3.2.1
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
  build_web_compilers: ^3.2.7

flutter:
  uses-material-design: true
  fonts:
    - family: Agave
      fonts:
        - asset: assets/Agave-Regular.ttf

flutter_gen:
  output: lib/res
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter_launcher_icons:
  image_path: "assets/JSON.png"
  remove_alpha_ios: true
  android:
    generate: true
  ios:
    generate: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
