name: json_example
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  json:
    path: ../

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
