name: json
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.4.1
  build: ^2.3.1
  json_core: ^0.1.0

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.1
  test: ^1.24.2

executables:
  jsond: json
