name: json_core
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  antlr4: ^4.12.0
  recase: ^4.1.0
  collection: ^1.17.0
  meta: ^1.8.0
  mustache_template: ^2.0.0
  code_builder: ^4.4.0
  dart_style: ^2.3.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
